/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CalloutPickerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  calloutTitles: {},
  language: "auto"
};

// src/i18n.ts
var translations = {
  tr: {
    commandName: "Callout Se\xE7ici",
    contextMenuLabel: "Callout Ekle",
    modalTitle: "Callout Se\xE7",
    settingsTitle: "Callout Se\xE7ici Ayarlar\u0131",
    settingsDesc: "Her callout t\xFCr\xFC i\xE7in varsay\u0131lan ba\u015Fl\u0131k belirleyin.",
    settingsTitleField: "Varsay\u0131lan Ba\u015Fl\u0131k",
    settingsPlaceholder: "Varsay\u0131lan ba\u015Fl\u0131k (iste\u011Fe ba\u011Fl\u0131)",
    settingsLanguageLabel: "Dil",
    settingsLanguageDesc: "Eklenti aray\xFCz dilini se\xE7in.",
    langAuto: "Otomatik (Obsidian dili)",
    langTr: "T\xFCrk\xE7e",
    langEn: "\u0130ngilizce",
    aliasesLabel: "Di\u011Fer adlar"
  },
  en: {
    commandName: "Callout Picker",
    contextMenuLabel: "Insert Callout",
    modalTitle: "Pick a Callout",
    settingsTitle: "Callout Picker Settings",
    settingsDesc: "Set a default title for each callout type.",
    settingsTitleField: "Default Title",
    settingsPlaceholder: "Default title (optional)",
    settingsLanguageLabel: "Language",
    settingsLanguageDesc: "Choose the plugin interface language.",
    langAuto: "Auto (follow Obsidian)",
    langTr: "Turkish",
    langEn: "English",
    aliasesLabel: "Aliases"
  }
};
function detectLocale() {
  var _a, _b, _c, _d;
  const lang = (_d = (_c = (_b = (_a = window.moment) == null ? void 0 : _a.locale) == null ? void 0 : _b.call(_a)) != null ? _c : navigator.language) != null ? _d : "en";
  return lang.startsWith("tr") ? "tr" : "en";
}
function t(locale) {
  var _a;
  return (_a = translations[locale]) != null ? _a : translations["en"];
}

// src/CalloutPickerModal.ts
var import_obsidian = require("obsidian");

// node_modules/svelte/src/runtime/internal/utils.js
function noop() {
}
function run(fn) {
  return fn();
}
function blank_object() {
  return /* @__PURE__ */ Object.create(null);
}
function run_all(fns) {
  fns.forEach(run);
}
function is_function(thing) {
  return typeof thing === "function";
}
function safe_not_equal(a, b) {
  return a != a ? b == b : a !== b || a && typeof a === "object" || typeof a === "function";
}
function is_empty(obj) {
  return Object.keys(obj).length === 0;
}

// node_modules/svelte/src/runtime/internal/globals.js
var globals = typeof window !== "undefined" ? window : typeof globalThis !== "undefined" ? globalThis : (
  // @ts-ignore Node typings have this
  global
);

// node_modules/svelte/src/runtime/internal/ResizeObserverSingleton.js
var ResizeObserverSingleton = class _ResizeObserverSingleton {
  /** @param {ResizeObserverOptions} options */
  constructor(options) {
    /**
     * @private
     * @readonly
     * @type {WeakMap<Element, import('./private.js').Listener>}
     */
    __publicField(this, "_listeners", "WeakMap" in globals ? /* @__PURE__ */ new WeakMap() : void 0);
    /**
     * @private
     * @type {ResizeObserver}
     */
    __publicField(this, "_observer");
    /** @type {ResizeObserverOptions} */
    __publicField(this, "options");
    this.options = options;
  }
  /**
   * @param {Element} element
   * @param {import('./private.js').Listener} listener
   * @returns {() => void}
   */
  observe(element2, listener) {
    this._listeners.set(element2, listener);
    this._getObserver().observe(element2, this.options);
    return () => {
      this._listeners.delete(element2);
      this._observer.unobserve(element2);
    };
  }
  /**
   * @private
   */
  _getObserver() {
    var _a;
    return (_a = this._observer) != null ? _a : this._observer = new ResizeObserver((entries) => {
      var _a2;
      for (const entry of entries) {
        _ResizeObserverSingleton.entries.set(entry.target, entry);
        (_a2 = this._listeners.get(entry.target)) == null ? void 0 : _a2(entry);
      }
    });
  }
};
ResizeObserverSingleton.entries = "WeakMap" in globals ? /* @__PURE__ */ new WeakMap() : void 0;

// node_modules/svelte/src/runtime/internal/dom.js
var is_hydrating = false;
function start_hydrating() {
  is_hydrating = true;
}
function end_hydrating() {
  is_hydrating = false;
}
function append(target, node) {
  target.appendChild(node);
}
function append_styles(target, style_sheet_id, styles) {
  const append_styles_to = get_root_for_style(target);
  if (!append_styles_to.getElementById(style_sheet_id)) {
    const style = element("style");
    style.id = style_sheet_id;
    style.textContent = styles;
    append_stylesheet(append_styles_to, style);
  }
}
function get_root_for_style(node) {
  if (!node) return document;
  const root = node.getRootNode ? node.getRootNode() : node.ownerDocument;
  if (root && /** @type {ShadowRoot} */
  root.host) {
    return (
      /** @type {ShadowRoot} */
      root
    );
  }
  return node.ownerDocument;
}
function append_stylesheet(node, style) {
  append(
    /** @type {Document} */
    node.head || node,
    style
  );
  return style.sheet;
}
function insert(target, node, anchor) {
  target.insertBefore(node, anchor || null);
}
function detach(node) {
  if (node.parentNode) {
    node.parentNode.removeChild(node);
  }
}
function destroy_each(iterations, detaching) {
  for (let i = 0; i < iterations.length; i += 1) {
    if (iterations[i]) iterations[i].d(detaching);
  }
}
function element(name) {
  return document.createElement(name);
}
function svg_element(name) {
  return document.createElementNS("http://www.w3.org/2000/svg", name);
}
function text(data) {
  return document.createTextNode(data);
}
function space() {
  return text(" ");
}
function listen(node, event, handler, options) {
  node.addEventListener(event, handler, options);
  return () => node.removeEventListener(event, handler, options);
}
function attr(node, attribute, value) {
  if (value == null) node.removeAttribute(attribute);
  else if (node.getAttribute(attribute) !== value) node.setAttribute(attribute, value);
}
function children(element2) {
  return Array.from(element2.childNodes);
}
function set_data(text2, data) {
  data = "" + data;
  if (text2.data === data) return;
  text2.data = /** @type {string} */
  data;
}
function set_style(node, key, value, important) {
  if (value == null) {
    node.style.removeProperty(key);
  } else {
    node.style.setProperty(key, value, important ? "important" : "");
  }
}
function toggle_class(element2, name, toggle) {
  element2.classList.toggle(name, !!toggle);
}
function get_custom_elements_slots(element2) {
  const result = {};
  element2.childNodes.forEach(
    /** @param {Element} node */
    (node) => {
      result[node.slot || "default"] = true;
    }
  );
  return result;
}

// node_modules/svelte/src/runtime/internal/lifecycle.js
var current_component;
function set_current_component(component) {
  current_component = component;
}
function get_current_component() {
  if (!current_component) throw new Error("Function called outside component initialization");
  return current_component;
}
function onMount(fn) {
  get_current_component().$$.on_mount.push(fn);
}

// node_modules/svelte/src/runtime/internal/scheduler.js
var dirty_components = [];
var binding_callbacks = [];
var render_callbacks = [];
var flush_callbacks = [];
var resolved_promise = /* @__PURE__ */ Promise.resolve();
var update_scheduled = false;
function schedule_update() {
  if (!update_scheduled) {
    update_scheduled = true;
    resolved_promise.then(flush);
  }
}
function add_render_callback(fn) {
  render_callbacks.push(fn);
}
var seen_callbacks = /* @__PURE__ */ new Set();
var flushidx = 0;
function flush() {
  if (flushidx !== 0) {
    return;
  }
  const saved_component = current_component;
  do {
    try {
      while (flushidx < dirty_components.length) {
        const component = dirty_components[flushidx];
        flushidx++;
        set_current_component(component);
        update(component.$$);
      }
    } catch (e) {
      dirty_components.length = 0;
      flushidx = 0;
      throw e;
    }
    set_current_component(null);
    dirty_components.length = 0;
    flushidx = 0;
    while (binding_callbacks.length) binding_callbacks.pop()();
    for (let i = 0; i < render_callbacks.length; i += 1) {
      const callback = render_callbacks[i];
      if (!seen_callbacks.has(callback)) {
        seen_callbacks.add(callback);
        callback();
      }
    }
    render_callbacks.length = 0;
  } while (dirty_components.length);
  while (flush_callbacks.length) {
    flush_callbacks.pop()();
  }
  update_scheduled = false;
  seen_callbacks.clear();
  set_current_component(saved_component);
}
function update($$) {
  if ($$.fragment !== null) {
    $$.update();
    run_all($$.before_update);
    const dirty = $$.dirty;
    $$.dirty = [-1];
    $$.fragment && $$.fragment.p($$.ctx, dirty);
    $$.after_update.forEach(add_render_callback);
  }
}
function flush_render_callbacks(fns) {
  const filtered = [];
  const targets = [];
  render_callbacks.forEach((c) => fns.indexOf(c) === -1 ? filtered.push(c) : targets.push(c));
  targets.forEach((c) => c());
  render_callbacks = filtered;
}

// node_modules/svelte/src/runtime/internal/transitions.js
var outroing = /* @__PURE__ */ new Set();
function transition_in(block, local) {
  if (block && block.i) {
    outroing.delete(block);
    block.i(local);
  }
}

// node_modules/svelte/src/runtime/internal/each.js
function ensure_array_like(array_like_or_iterator) {
  return (array_like_or_iterator == null ? void 0 : array_like_or_iterator.length) !== void 0 ? array_like_or_iterator : Array.from(array_like_or_iterator);
}

// node_modules/svelte/src/shared/boolean_attributes.js
var _boolean_attributes = (
  /** @type {const} */
  [
    "allowfullscreen",
    "allowpaymentrequest",
    "async",
    "autofocus",
    "autoplay",
    "checked",
    "controls",
    "default",
    "defer",
    "disabled",
    "formnovalidate",
    "hidden",
    "inert",
    "ismap",
    "loop",
    "multiple",
    "muted",
    "nomodule",
    "novalidate",
    "open",
    "playsinline",
    "readonly",
    "required",
    "reversed",
    "selected"
  ]
);
var boolean_attributes = /* @__PURE__ */ new Set([..._boolean_attributes]);

// node_modules/svelte/src/runtime/internal/Component.js
function mount_component(component, target, anchor) {
  const { fragment, after_update } = component.$$;
  fragment && fragment.m(target, anchor);
  add_render_callback(() => {
    const new_on_destroy = component.$$.on_mount.map(run).filter(is_function);
    if (component.$$.on_destroy) {
      component.$$.on_destroy.push(...new_on_destroy);
    } else {
      run_all(new_on_destroy);
    }
    component.$$.on_mount = [];
  });
  after_update.forEach(add_render_callback);
}
function destroy_component(component, detaching) {
  const $$ = component.$$;
  if ($$.fragment !== null) {
    flush_render_callbacks($$.after_update);
    run_all($$.on_destroy);
    $$.fragment && $$.fragment.d(detaching);
    $$.on_destroy = $$.fragment = null;
    $$.ctx = [];
  }
}
function make_dirty(component, i) {
  if (component.$$.dirty[0] === -1) {
    dirty_components.push(component);
    schedule_update();
    component.$$.dirty.fill(0);
  }
  component.$$.dirty[i / 31 | 0] |= 1 << i % 31;
}
function init(component, options, instance2, create_fragment2, not_equal, props, append_styles2 = null, dirty = [-1]) {
  const parent_component = current_component;
  set_current_component(component);
  const $$ = component.$$ = {
    fragment: null,
    ctx: [],
    // state
    props,
    update: noop,
    not_equal,
    bound: blank_object(),
    // lifecycle
    on_mount: [],
    on_destroy: [],
    on_disconnect: [],
    before_update: [],
    after_update: [],
    context: new Map(options.context || (parent_component ? parent_component.$$.context : [])),
    // everything else
    callbacks: blank_object(),
    dirty,
    skip_bound: false,
    root: options.target || parent_component.$$.root
  };
  append_styles2 && append_styles2($$.root);
  let ready = false;
  $$.ctx = instance2 ? instance2(component, options.props || {}, (i, ret, ...rest) => {
    const value = rest.length ? rest[0] : ret;
    if ($$.ctx && not_equal($$.ctx[i], $$.ctx[i] = value)) {
      if (!$$.skip_bound && $$.bound[i]) $$.bound[i](value);
      if (ready) make_dirty(component, i);
    }
    return ret;
  }) : [];
  $$.update();
  ready = true;
  run_all($$.before_update);
  $$.fragment = create_fragment2 ? create_fragment2($$.ctx) : false;
  if (options.target) {
    if (options.hydrate) {
      start_hydrating();
      const nodes = children(options.target);
      $$.fragment && $$.fragment.l(nodes);
      nodes.forEach(detach);
    } else {
      $$.fragment && $$.fragment.c();
    }
    if (options.intro) transition_in(component.$$.fragment);
    mount_component(component, options.target, options.anchor);
    end_hydrating();
    flush();
  }
  set_current_component(parent_component);
}
var SvelteElement;
if (typeof HTMLElement === "function") {
  SvelteElement = class extends HTMLElement {
    constructor($$componentCtor, $$slots, use_shadow_dom) {
      super();
      /** The Svelte component constructor */
      __publicField(this, "$$ctor");
      /** Slots */
      __publicField(this, "$$s");
      /** The Svelte component instance */
      __publicField(this, "$$c");
      /** Whether or not the custom element is connected */
      __publicField(this, "$$cn", false);
      /** Component props data */
      __publicField(this, "$$d", {});
      /** `true` if currently in the process of reflecting component props back to attributes */
      __publicField(this, "$$r", false);
      /** @type {Record<string, CustomElementPropDefinition>} Props definition (name, reflected, type etc) */
      __publicField(this, "$$p_d", {});
      /** @type {Record<string, Function[]>} Event listeners */
      __publicField(this, "$$l", {});
      /** @type {Map<Function, Function>} Event listener unsubscribe functions */
      __publicField(this, "$$l_u", /* @__PURE__ */ new Map());
      this.$$ctor = $$componentCtor;
      this.$$s = $$slots;
      if (use_shadow_dom) {
        this.attachShadow({ mode: "open" });
      }
    }
    addEventListener(type, listener, options) {
      this.$$l[type] = this.$$l[type] || [];
      this.$$l[type].push(listener);
      if (this.$$c) {
        const unsub = this.$$c.$on(type, listener);
        this.$$l_u.set(listener, unsub);
      }
      super.addEventListener(type, listener, options);
    }
    removeEventListener(type, listener, options) {
      super.removeEventListener(type, listener, options);
      if (this.$$c) {
        const unsub = this.$$l_u.get(listener);
        if (unsub) {
          unsub();
          this.$$l_u.delete(listener);
        }
      }
      if (this.$$l[type]) {
        const idx = this.$$l[type].indexOf(listener);
        if (idx >= 0) {
          this.$$l[type].splice(idx, 1);
        }
      }
    }
    async connectedCallback() {
      this.$$cn = true;
      if (!this.$$c) {
        let create_slot = function(name) {
          return () => {
            let node;
            const obj = {
              c: function create() {
                node = element("slot");
                if (name !== "default") {
                  attr(node, "name", name);
                }
              },
              /**
               * @param {HTMLElement} target
               * @param {HTMLElement} [anchor]
               */
              m: function mount(target, anchor) {
                insert(target, node, anchor);
              },
              d: function destroy(detaching) {
                if (detaching) {
                  detach(node);
                }
              }
            };
            return obj;
          };
        };
        await Promise.resolve();
        if (!this.$$cn || this.$$c) {
          return;
        }
        const $$slots = {};
        const existing_slots = get_custom_elements_slots(this);
        for (const name of this.$$s) {
          if (name in existing_slots) {
            $$slots[name] = [create_slot(name)];
          }
        }
        for (const attribute of this.attributes) {
          const name = this.$$g_p(attribute.name);
          if (!(name in this.$$d)) {
            this.$$d[name] = get_custom_element_value(name, attribute.value, this.$$p_d, "toProp");
          }
        }
        for (const key in this.$$p_d) {
          if (!(key in this.$$d) && this[key] !== void 0) {
            this.$$d[key] = this[key];
            delete this[key];
          }
        }
        this.$$c = new this.$$ctor({
          target: this.shadowRoot || this,
          props: {
            ...this.$$d,
            $$slots,
            $$scope: {
              ctx: []
            }
          }
        });
        const reflect_attributes = () => {
          this.$$r = true;
          for (const key in this.$$p_d) {
            this.$$d[key] = this.$$c.$$.ctx[this.$$c.$$.props[key]];
            if (this.$$p_d[key].reflect) {
              const attribute_value = get_custom_element_value(
                key,
                this.$$d[key],
                this.$$p_d,
                "toAttribute"
              );
              if (attribute_value == null) {
                this.removeAttribute(this.$$p_d[key].attribute || key);
              } else {
                this.setAttribute(this.$$p_d[key].attribute || key, attribute_value);
              }
            }
          }
          this.$$r = false;
        };
        this.$$c.$$.after_update.push(reflect_attributes);
        reflect_attributes();
        for (const type in this.$$l) {
          for (const listener of this.$$l[type]) {
            const unsub = this.$$c.$on(type, listener);
            this.$$l_u.set(listener, unsub);
          }
        }
        this.$$l = {};
      }
    }
    // We don't need this when working within Svelte code, but for compatibility of people using this outside of Svelte
    // and setting attributes through setAttribute etc, this is helpful
    attributeChangedCallback(attr2, _oldValue, newValue) {
      var _a;
      if (this.$$r) return;
      attr2 = this.$$g_p(attr2);
      this.$$d[attr2] = get_custom_element_value(attr2, newValue, this.$$p_d, "toProp");
      (_a = this.$$c) == null ? void 0 : _a.$set({ [attr2]: this.$$d[attr2] });
    }
    disconnectedCallback() {
      this.$$cn = false;
      Promise.resolve().then(() => {
        if (!this.$$cn && this.$$c) {
          this.$$c.$destroy();
          this.$$c = void 0;
        }
      });
    }
    $$g_p(attribute_name) {
      return Object.keys(this.$$p_d).find(
        (key) => this.$$p_d[key].attribute === attribute_name || !this.$$p_d[key].attribute && key.toLowerCase() === attribute_name
      ) || attribute_name;
    }
  };
}
function get_custom_element_value(prop, value, props_definition, transform) {
  var _a;
  const type = (_a = props_definition[prop]) == null ? void 0 : _a.type;
  value = type === "Boolean" && typeof value !== "boolean" ? value != null : value;
  if (!transform || !props_definition[prop]) {
    return value;
  } else if (transform === "toAttribute") {
    switch (type) {
      case "Object":
      case "Array":
        return value == null ? null : JSON.stringify(value);
      case "Boolean":
        return value ? "" : null;
      case "Number":
        return value == null ? null : value;
      default:
        return value;
    }
  } else {
    switch (type) {
      case "Object":
      case "Array":
        return value && JSON.parse(value);
      case "Boolean":
        return value;
      case "Number":
        return value != null ? +value : value;
      default:
        return value;
    }
  }
}
var SvelteComponent = class {
  constructor() {
    /**
     * ### PRIVATE API
     *
     * Do not use, may change at any time
     *
     * @type {any}
     */
    __publicField(this, "$$");
    /**
     * ### PRIVATE API
     *
     * Do not use, may change at any time
     *
     * @type {any}
     */
    __publicField(this, "$$set");
  }
  /** @returns {void} */
  $destroy() {
    destroy_component(this, 1);
    this.$destroy = noop;
  }
  /**
   * @template {Extract<keyof Events, string>} K
   * @param {K} type
   * @param {((e: Events[K]) => void) | null | undefined} callback
   * @returns {() => void}
   */
  $on(type, callback) {
    if (!is_function(callback)) {
      return noop;
    }
    const callbacks = this.$$.callbacks[type] || (this.$$.callbacks[type] = []);
    callbacks.push(callback);
    return () => {
      const index = callbacks.indexOf(callback);
      if (index !== -1) callbacks.splice(index, 1);
    };
  }
  /**
   * @param {Partial<Props>} props
   * @returns {void}
   */
  $set(props) {
    if (this.$$set && !is_empty(props)) {
      this.$$.skip_bound = true;
      this.$$set(props);
      this.$$.skip_bound = false;
    }
  }
};

// node_modules/svelte/src/shared/version.js
var PUBLIC_VERSION = "4";

// node_modules/svelte/src/runtime/internal/disclose-version/index.js
if (typeof window !== "undefined")
  (window.__svelte || (window.__svelte = { v: /* @__PURE__ */ new Set() })).v.add(PUBLIC_VERSION);

// src/calloutData.ts
var CALLOUTS = [
  {
    id: "note",
    aliases: [],
    color: "#448aff",
    icon: "pencil",
    iconPath: "M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z M15 5l4 4"
  },
  {
    id: "abstract",
    aliases: ["summary", "tldr"],
    color: "#00b0ff",
    icon: "clipboard-list",
    iconPath: "M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2 M9 2h6a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1z M9 12h6 M9 16h6 M9 8h2"
  },
  {
    id: "info",
    aliases: [],
    color: "#00b0ff",
    icon: "info",
    iconPath: "M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20z M12 16v-4 M12 8h.01"
  },
  {
    id: "todo",
    aliases: [],
    color: "#448aff",
    icon: "check-circle-2",
    iconPath: "M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20z M9 12l2 2 4-4"
  },
  {
    id: "tip",
    aliases: ["hint", "important"],
    color: "#00bcd4",
    icon: "flame",
    iconPath: "M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5z"
  },
  {
    id: "success",
    aliases: ["check", "done"],
    color: "#00c853",
    icon: "check",
    iconPath: "M20 6 9 17l-5-5"
  },
  {
    id: "question",
    aliases: ["help", "faq"],
    color: "#64dd17",
    icon: "help-circle",
    iconPath: "M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20z M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3 M12 17h.01"
  },
  {
    id: "warning",
    aliases: ["caution", "attention"],
    color: "#ff9100",
    icon: "alert-triangle",
    iconPath: "m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3 M12 9v4 M12 17h.01"
  },
  {
    id: "failure",
    aliases: ["fail", "missing"],
    color: "#ff5252",
    icon: "x",
    iconPath: "M18 6 6 18 M6 6l12 12"
  },
  {
    id: "danger",
    aliases: ["error"],
    color: "#ff1744",
    icon: "zap",
    iconPath: "M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z"
  },
  {
    id: "bug",
    aliases: [],
    color: "#f50057",
    icon: "bug",
    iconPath: "m8 2 1.88 1.88 M14.12 3.88 16 2 M9 7.13v-1a3.003 3.003 0 1 1 6 0v1 M12 20c-3.3 0-6-2.7-6-6v-3a4 4 0 0 1 4-4h4a4 4 0 0 1 4 4v3c0 3.3-2.7 6-6 6 M12 20v-9 M6.53 9C4.6 8.8 3 7.1 3 5 M6 13H2 M3 21c0-3 1.5-6 4-8 M20.47 9C22.4 8.8 24 7.1 24 5 M22 13h-4 M21 21c0-3-1.5-6-4-8"
  },
  {
    id: "example",
    aliases: [],
    color: "#7c4dff",
    icon: "list",
    iconPath: "M3 12h.01 M3 18h.01 M3 6h.01 M8 12h13 M8 18h13 M8 6h13"
  },
  {
    id: "quote",
    aliases: ["cite"],
    color: "#9e9e9e",
    icon: "quote",
    iconPath: "3 21c-1 0-1.5-.5-1.5-1.5v-4c0-1 .5-2 1.5-2h4c1 0 1.5.5 1.5 1.5v4C9 20.5 8.5 21 7.5 21H3zM3 3.5C3 2.5 3.5 2 4.5 2h4C9.5 2 10 2.5 10 3.5V7c0 1-.5 1.5-1.5 1.5h-4C3.5 8.5 3 8 3 7V3.5zM14 21c-1 0-1.5-.5-1.5-1.5v-4c0-1 .5-2 1.5-2h4c1 0 1.5.5 1.5 1.5v4c0 1-.5 1.5-1.5 1.5h-4zM14 3.5C14 2.5 14.5 2 15.5 2h4C20.5 2 21 2.5 21 3.5V7c0 1-.5 1.5-1.5 1.5h-4C14.5 8.5 14 8 14 7V3.5z"
  }
];

// src/components/CalloutPicker.svelte
function add_css(target) {
  append_styles(target, "svelte-yv8txg", ".cp-header.svelte-yv8txg{display:flex;align-items:center;justify-content:space-between;padding:0 4px 10px;border-bottom:1px solid var(--background-modifier-border);margin-bottom:12px}.cp-title.svelte-yv8txg{font-size:0.9em;font-weight:600;color:var(--text-muted);text-transform:uppercase;letter-spacing:0.06em}.cp-hint.svelte-yv8txg{font-size:0.75em;color:var(--text-faint);background:var(--background-modifier-hover);border:1px solid var(--background-modifier-border);border-radius:4px;padding:1px 5px;font-family:var(--font-monospace)}.cp-grid.svelte-yv8txg{display:grid;grid-template-columns:repeat(3, 1fr);gap:8px;outline:none}.cp-card.svelte-yv8txg{position:relative;display:flex;align-items:stretch;border-radius:6px;border:2px solid transparent;background:var(--background-secondary);cursor:pointer;transition:border-color 0.1s, background 0.1s;overflow:hidden;min-height:70px}.cp-card.svelte-yv8txg:hover,.cp-card--focused.svelte-yv8txg{border-color:var(--callout-color);background:var(--background-secondary-alt)}.cp-card__accent.svelte-yv8txg{width:4px;flex-shrink:0;background:var(--callout-color)}.cp-card__body.svelte-yv8txg{display:flex;flex-direction:column;justify-content:center;gap:2px;padding:8px 10px;flex:1;overflow:hidden}.cp-card__icon.svelte-yv8txg{width:16px;height:16px;color:var(--callout-color);flex-shrink:0;margin-bottom:2px}.cp-card__name.svelte-yv8txg{font-size:0.85em;font-weight:600;color:var(--text-normal);text-transform:capitalize;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cp-card__aliases.svelte-yv8txg{font-size:0.7em;color:var(--text-faint);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cp-card__default-title.svelte-yv8txg{font-size:0.7em;color:var(--callout-color);font-style:italic;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}");
}
function get_each_context(ctx, list, i) {
  const child_ctx = ctx.slice();
  child_ctx[12] = list[i];
  child_ctx[14] = i;
  return child_ctx;
}
function create_if_block_1(ctx) {
  let span;
  return {
    c() {
      span = element("span");
      span.textContent = `${/*callout*/
      ctx[12].aliases.join(", ")}`;
      attr(span, "class", "cp-card__aliases svelte-yv8txg");
    },
    m(target, anchor) {
      insert(target, span, anchor);
    },
    d(detaching) {
      if (detaching) {
        detach(span);
      }
    }
  };
}
function create_if_block(ctx) {
  let span;
  let t0;
  let t1_value = (
    /*settings*/
    ctx[0].calloutTitles[
      /*callout*/
      ctx[12].id
    ] + ""
  );
  let t1;
  let t2;
  return {
    c() {
      span = element("span");
      t0 = text('"');
      t1 = text(t1_value);
      t2 = text('"');
      attr(span, "class", "cp-card__default-title svelte-yv8txg");
    },
    m(target, anchor) {
      insert(target, span, anchor);
      append(span, t0);
      append(span, t1);
      append(span, t2);
    },
    p(ctx2, dirty) {
      if (dirty & /*settings*/
      1 && t1_value !== (t1_value = /*settings*/
      ctx2[0].calloutTitles[
        /*callout*/
        ctx2[12].id
      ] + "")) set_data(t1, t1_value);
    },
    d(detaching) {
      if (detaching) {
        detach(span);
      }
    }
  };
}
function create_each_block(ctx) {
  let div2;
  let div0;
  let t0;
  let div1;
  let svg;
  let path;
  let path_d_value;
  let t1;
  let span;
  let t3;
  let t4;
  let t5;
  let div2_aria_selected_value;
  let mounted;
  let dispose;
  let if_block0 = (
    /*callout*/
    ctx[12].aliases.length > 0 && create_if_block_1(ctx)
  );
  let if_block1 = (
    /*settings*/
    ctx[0].calloutTitles[
      /*callout*/
      ctx[12].id
    ] && create_if_block(ctx)
  );
  function click_handler() {
    return (
      /*click_handler*/
      ctx[9](
        /*i*/
        ctx[14]
      )
    );
  }
  function mouseenter_handler() {
    return (
      /*mouseenter_handler*/
      ctx[10](
        /*i*/
        ctx[14]
      )
    );
  }
  return {
    c() {
      div2 = element("div");
      div0 = element("div");
      t0 = space();
      div1 = element("div");
      svg = svg_element("svg");
      path = svg_element("path");
      t1 = space();
      span = element("span");
      span.textContent = `${/*callout*/
      ctx[12].id}`;
      t3 = space();
      if (if_block0) if_block0.c();
      t4 = space();
      if (if_block1) if_block1.c();
      t5 = space();
      attr(div0, "class", "cp-card__accent svelte-yv8txg");
      attr(path, "d", path_d_value = /*callout*/
      ctx[12].iconPath);
      attr(svg, "class", "cp-card__icon svelte-yv8txg");
      attr(svg, "viewBox", "0 0 24 24");
      attr(svg, "fill", "none");
      attr(svg, "stroke", "currentColor");
      attr(svg, "stroke-width", "2");
      attr(svg, "stroke-linecap", "round");
      attr(svg, "stroke-linejoin", "round");
      attr(svg, "aria-hidden", "true");
      attr(span, "class", "cp-card__name svelte-yv8txg");
      attr(div1, "class", "cp-card__body svelte-yv8txg");
      attr(div2, "class", "cp-card svelte-yv8txg");
      attr(div2, "role", "option");
      attr(div2, "aria-selected", div2_aria_selected_value = /*focusedIndex*/
      ctx[1] === /*i*/
      ctx[14]);
      attr(div2, "tabindex", "-1");
      set_style(
        div2,
        "--callout-color",
        /*callout*/
        ctx[12].color
      );
      toggle_class(
        div2,
        "cp-card--focused",
        /*focusedIndex*/
        ctx[1] === /*i*/
        ctx[14]
      );
    },
    m(target, anchor) {
      insert(target, div2, anchor);
      append(div2, div0);
      append(div2, t0);
      append(div2, div1);
      append(div1, svg);
      append(svg, path);
      append(div1, t1);
      append(div1, span);
      append(div1, t3);
      if (if_block0) if_block0.m(div1, null);
      append(div1, t4);
      if (if_block1) if_block1.m(div1, null);
      append(div2, t5);
      if (!mounted) {
        dispose = [
          listen(div2, "click", click_handler),
          listen(div2, "mouseenter", mouseenter_handler)
        ];
        mounted = true;
      }
    },
    p(new_ctx, dirty) {
      ctx = new_ctx;
      if (
        /*settings*/
        ctx[0].calloutTitles[
          /*callout*/
          ctx[12].id
        ]
      ) {
        if (if_block1) {
          if_block1.p(ctx, dirty);
        } else {
          if_block1 = create_if_block(ctx);
          if_block1.c();
          if_block1.m(div1, null);
        }
      } else if (if_block1) {
        if_block1.d(1);
        if_block1 = null;
      }
      if (dirty & /*focusedIndex*/
      2 && div2_aria_selected_value !== (div2_aria_selected_value = /*focusedIndex*/
      ctx[1] === /*i*/
      ctx[14])) {
        attr(div2, "aria-selected", div2_aria_selected_value);
      }
      if (dirty & /*focusedIndex*/
      2) {
        toggle_class(
          div2,
          "cp-card--focused",
          /*focusedIndex*/
          ctx[1] === /*i*/
          ctx[14]
        );
      }
    },
    d(detaching) {
      if (detaching) {
        detach(div2);
      }
      if (if_block0) if_block0.d();
      if (if_block1) if_block1.d();
      mounted = false;
      run_all(dispose);
    }
  };
}
function create_fragment(ctx) {
  let div0;
  let span;
  let t0_value = (
    /*strings*/
    ctx[3].modalTitle + ""
  );
  let t0;
  let t1;
  let kbd;
  let t3;
  let div1;
  let mounted;
  let dispose;
  let each_value = ensure_array_like(CALLOUTS);
  let each_blocks = [];
  for (let i = 0; i < each_value.length; i += 1) {
    each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
  }
  return {
    c() {
      div0 = element("div");
      span = element("span");
      t0 = text(t0_value);
      t1 = space();
      kbd = element("kbd");
      kbd.textContent = "\u2191\u2193\u2190\u2192 \xB7 Enter";
      t3 = space();
      div1 = element("div");
      for (let i = 0; i < each_blocks.length; i += 1) {
        each_blocks[i].c();
      }
      attr(span, "class", "cp-title svelte-yv8txg");
      attr(kbd, "class", "cp-hint svelte-yv8txg");
      attr(div0, "class", "cp-header svelte-yv8txg");
      attr(div0, "role", "banner");
      attr(div1, "class", "cp-grid svelte-yv8txg");
      attr(div1, "role", "listbox");
      attr(div1, "tabindex", "0");
    },
    m(target, anchor) {
      insert(target, div0, anchor);
      append(div0, span);
      append(span, t0);
      append(div0, t1);
      append(div0, kbd);
      insert(target, t3, anchor);
      insert(target, div1, anchor);
      for (let i = 0; i < each_blocks.length; i += 1) {
        if (each_blocks[i]) {
          each_blocks[i].m(div1, null);
        }
      }
      ctx[11](div1);
      if (!mounted) {
        dispose = listen(
          div1,
          "keydown",
          /*handleKeydown*/
          ctx[4]
        );
        mounted = true;
      }
    },
    p(ctx2, [dirty]) {
      if (dirty & /*strings*/
      8 && t0_value !== (t0_value = /*strings*/
      ctx2[3].modalTitle + "")) set_data(t0, t0_value);
      if (dirty & /*focusedIndex, handleCardClick, settings*/
      35) {
        each_value = ensure_array_like(CALLOUTS);
        let i;
        for (i = 0; i < each_value.length; i += 1) {
          const child_ctx = get_each_context(ctx2, each_value, i);
          if (each_blocks[i]) {
            each_blocks[i].p(child_ctx, dirty);
          } else {
            each_blocks[i] = create_each_block(child_ctx);
            each_blocks[i].c();
            each_blocks[i].m(div1, null);
          }
        }
        for (; i < each_blocks.length; i += 1) {
          each_blocks[i].d(1);
        }
        each_blocks.length = each_value.length;
      }
    },
    i: noop,
    o: noop,
    d(detaching) {
      if (detaching) {
        detach(div0);
        detach(t3);
        detach(div1);
      }
      destroy_each(each_blocks, detaching);
      ctx[11](null);
      mounted = false;
      dispose();
    }
  };
}
function instance($$self, $$props, $$invalidate) {
  let strings;
  let { settings } = $$props;
  let { locale } = $$props;
  let { onSelect } = $$props;
  let { onClose } = $$props;
  let focusedIndex = 0;
  let gridEl;
  onMount(() => {
    gridEl === null || gridEl === void 0 ? void 0 : gridEl.focus();
  });
  function handleKeydown(event) {
    const cols = 3;
    const count = CALLOUTS.length;
    switch (event.key) {
      case "ArrowRight":
        event.preventDefault();
        $$invalidate(1, focusedIndex = (focusedIndex + 1) % count);
        break;
      case "ArrowLeft":
        event.preventDefault();
        $$invalidate(1, focusedIndex = (focusedIndex - 1 + count) % count);
        break;
      case "ArrowDown":
        event.preventDefault();
        $$invalidate(1, focusedIndex = Math.min(focusedIndex + cols, count - 1));
        break;
      case "ArrowUp":
        event.preventDefault();
        $$invalidate(1, focusedIndex = Math.max(focusedIndex - cols, 0));
        break;
      case "Enter":
      case " ":
        event.preventDefault();
        onSelect(CALLOUTS[focusedIndex].id);
        break;
      case "Escape":
        event.preventDefault();
        onClose();
        break;
    }
  }
  function handleCardClick(index) {
    $$invalidate(1, focusedIndex = index);
    onSelect(CALLOUTS[index].id);
  }
  const click_handler = (i) => handleCardClick(i);
  const mouseenter_handler = (i) => $$invalidate(1, focusedIndex = i);
  function div1_binding($$value) {
    binding_callbacks[$$value ? "unshift" : "push"](() => {
      gridEl = $$value;
      $$invalidate(2, gridEl);
    });
  }
  $$self.$$set = ($$props2) => {
    if ("settings" in $$props2) $$invalidate(0, settings = $$props2.settings);
    if ("locale" in $$props2) $$invalidate(6, locale = $$props2.locale);
    if ("onSelect" in $$props2) $$invalidate(7, onSelect = $$props2.onSelect);
    if ("onClose" in $$props2) $$invalidate(8, onClose = $$props2.onClose);
  };
  $$self.$$.update = () => {
    if ($$self.$$.dirty & /*locale*/
    64) {
      $: $$invalidate(3, strings = t(locale));
    }
  };
  return [
    settings,
    focusedIndex,
    gridEl,
    strings,
    handleKeydown,
    handleCardClick,
    locale,
    onSelect,
    onClose,
    click_handler,
    mouseenter_handler,
    div1_binding
  ];
}
var CalloutPicker = class extends SvelteComponent {
  constructor(options) {
    super();
    init(
      this,
      options,
      instance,
      create_fragment,
      safe_not_equal,
      {
        settings: 0,
        locale: 6,
        onSelect: 7,
        onClose: 8
      },
      add_css
    );
  }
};
var CalloutPicker_default = CalloutPicker;

// src/CalloutPickerModal.ts
var CalloutPickerModal = class extends import_obsidian.Modal {
  constructor(app, editor, settings) {
    super(app);
    this.editor = editor;
    this.settings = settings;
    this.svelteComponent = null;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    this.modalEl.addClass("callout-picker-modal");
    const locale = this.settings.language === "auto" ? detectLocale() : this.settings.language;
    this.svelteComponent = new CalloutPicker_default({
      target: contentEl,
      props: {
        settings: this.settings,
        locale,
        onSelect: (calloutId) => {
          this.insertCallout(calloutId);
          this.close();
        },
        onClose: () => {
          this.close();
        }
      }
    });
  }
  onClose() {
    if (this.svelteComponent) {
      this.svelteComponent.$destroy();
      this.svelteComponent = null;
    }
    this.contentEl.empty();
  }
  insertCallout(calloutId) {
    var _a;
    const title = (_a = this.settings.calloutTitles[calloutId]) != null ? _a : "";
    const header = title ? `> [!${calloutId}] ${title}` : `> [!${calloutId}]`;
    const editor = this.editor;
    const selection = editor.getSelection();
    if (selection) {
      const lines = selection.split("\n");
      const wrapped = lines.map((line, i) => i === 0 ? `${header}
> ${line}` : `> ${line}`).join("\n");
      editor.replaceSelection(wrapped);
    } else {
      const cursor = editor.getCursor();
      editor.replaceRange(`${header}
> `, cursor);
      editor.setCursor({ line: cursor.line + 1, ch: 2 });
    }
  }
};

// src/SettingsTab.ts
var import_obsidian2 = require("obsidian");
var CalloutPickerSettingsTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const locale = this.plugin.settings.language === "auto" ? detectLocale() : this.plugin.settings.language;
    const strings = t(locale);
    containerEl.createEl("h2", { text: strings.settingsTitle });
    containerEl.createEl("p", { text: strings.settingsDesc, cls: "setting-item-description" });
    new import_obsidian2.Setting(containerEl).setName(strings.settingsLanguageLabel).setDesc(strings.settingsLanguageDesc).addDropdown((dropdown) => {
      dropdown.addOption("auto", strings.langAuto).addOption("tr", strings.langTr).addOption("en", strings.langEn).setValue(this.plugin.settings.language).onChange(async (value) => {
        this.plugin.settings.language = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    containerEl.createEl("hr");
    for (const callout of CALLOUTS) {
      const aliases = callout.aliases.length ? `  \u2014  ${strings.aliasesLabel}: ${callout.aliases.join(", ")}` : "";
      new import_obsidian2.Setting(containerEl).setName(callout.id.charAt(0).toUpperCase() + callout.id.slice(1)).setDesc(`[!${callout.id}]${aliases}`).addText((text2) => {
        var _a;
        text2.setPlaceholder(strings.settingsPlaceholder).setValue((_a = this.plugin.settings.calloutTitles[callout.id]) != null ? _a : "").onChange(async (value) => {
          if (value.trim()) {
            this.plugin.settings.calloutTitles[callout.id] = value.trim();
          } else {
            delete this.plugin.settings.calloutTitles[callout.id];
          }
          await this.plugin.saveSettings();
        });
      });
    }
  }
};

// src/main.ts
var CalloutPickerPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    const locale = this.settings.language === "auto" ? detectLocale() : this.settings.language;
    const strings = t(locale);
    this.addCommand({
      id: "open-callout-picker",
      name: strings.commandName,
      editorCallback: (editor) => {
        new CalloutPickerModal(this.app, editor, this.settings).open();
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        menu.addItem((item) => {
          item.setTitle(strings.contextMenuLabel).setIcon("box-select").onClick(() => new CalloutPickerModal(this.app, editor, this.settings).open());
        });
      })
    );
    this.addSettingTab(new CalloutPickerSettingsTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
